on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2
    - name: Place TG_PROPERTIES
      run: echo ${{ secrets.TG_PROPERTIES }} > src/main/resources/tg.properties
    - name: Yandex Cloud CR "Login" Action for GitHub Actions
      uses: yc-actions/yc-cr-login@v2.0.0
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS}}
    - name: Build, tag and push image to Yandex Cloud Container Registry
      env: 
        CR_REGISTRY: crpj474brk1fb602vqsb
        CR_REPO: binbot
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG .
        docker push cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG
